# application.yml

spring:
  application:
    name: SecondHandHouseBackend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SecondHandHouse?useSSL=false&serverTimezone=UTC
    username: root
    password: "1234"  # ?????????????


# MyBatis-Plus ??
mybatis-plus:
  configuration:
    # ??????
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    # ??MyBatis??
    map-underscore-to-camel-case: true  # ??????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ????

  # ????
  global-config:
    db-config:
      id-type: auto  # ????
      logic-delete-field: deleted  # ????????????
      logic-not-delete-value: 0    # ??????
      logic-delete-value: 1        # ?????

# ?????????
server:
  port: 8080
  servlet:
    context-path: /  # ???????